import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowUpRight, BadgeCheck, Banknote, Bot, ChevronRight, CircleDot, Crown, Hammer, Package, RefreshCw, Send, ShieldCheck, Sparkles, Store, WalletCards } from 'lucide-react';
import './styles.css';

const API = 'http://localhost:8000';
type Ticket = { id:number; type:string; requester:string; subject:string; sku?:string; size?:string; qty?:number; status:string; notes?:string };
type Event = { run_id:string; step:number; agent:string; action:string; detail:string; ticket_id?:number; tool_name?:string; result?:unknown; timestamp?:string };
type Cash = { name:string; balance:number; date:string };
const agents = ['boss','inventory','accounting','facilities','customer_service'];
const agentNames:Record<string,string> = { boss:'Boss', inventory:'Inventory', accounting:'Accounting', facilities:'Facilities', customer_service:'Customer Service' };
const icons:Record<string,React.ElementType> = { boss:Crown, inventory:Package, accounting:WalletCards, facilities:Store, customer_service:Send };
const colors:Record<string,string> = { boss:'gold', inventory:'green', accounting:'blue', facilities:'purple', customer_service:'rose' };

async function get<T>(path:string):Promise<T>{ const r=await fetch(API+path); if(!r.ok) throw new Error(await r.text()); return r.json(); }
function App(){
  const [tickets,setTickets]=useState<Ticket[]>([]), [selected,setSelected]=useState(101), [events,setEvents]=useState<Event[]>([]), [cash,setCash]=useState<Cash|null>(null), [running,setRunning]=useState(false), [message,setMessage]=useState('');
  const load=async()=>{ try { const [ts,ev,c]=await Promise.all([get<Ticket[]>('/api/tickets'),get<Event[]>('/api/agent-events?limit=120'),get<Cash>('/api/cash')]); setTickets(ts);setEvents(ev);setCash(c); } catch(e){setMessage('Backend is offline — start FastAPI on port 8000.')} };
  useEffect(()=>{load();const id=setInterval(load,1800);return()=>clearInterval(id)},[]);
  const ticket=tickets.find(t=>t.id===selected); const ticketEvents=useMemo(()=>events.filter(e=>e.ticket_id===selected),[events,selected]);
  const run=async()=>{setRunning(true);setMessage('The team is opening the ticket…');try{const r=await fetch(`${API}/api/tickets/${selected}/run`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requested_by:'desk operator'})});if(!r.ok)throw Error();setMessage('Run complete — Boss has posted a recommendation.');await load()}catch{setMessage('The team could not start. Check the backend.')}finally{setRunning(false)}};
  const approve=async()=>{const name=prompt('Enter your name to approve this payment:');if(!name)return;const r=await fetch(`${API}/api/approve-payment`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticket_id:selected,approved_by:name})});setMessage(r.ok?'Payment approved and cash updated.':await r.text());load()};
  const pendingApproval=ticketEvents.some(e=>e.action==='response'&&JSON.stringify(e.result??'').toLowerCase().includes('approval'));
  return <div className="app"><aside className="rail"><div className="mark"><span>✦</span></div><div className="rail-links"><div className="rail-link active"><Activity size={19}/><small>Desk</small></div><div className="rail-link"><Package size={19}/><small>Stock</small></div><div className="rail-link"><Banknote size={19}/><small>Cash</small></div></div><div className="rail-bottom"><ShieldCheck size={18}/><span>Safe mode</span></div></aside>
    <main><header className="topbar"><div><div className="kicker">Campus Customs / Operations room</div><h1>Good morning, captain.</h1><p>One clear decision at a time.</p></div><div className="live"><CircleDot size={12}/> LIVE DESK <span>•</span> {cash?.date??'—'}</div></header>
      <section className="stats"><div className="stat"><span>Open requests</span><strong>{tickets.filter(t=>t.status==='open').length}<em> / 3</em></strong><small>waiting for a decision</small></div><div className="stat balance"><span>Checking balance</span><strong>${cash?.balance.toLocaleString()??'—'}</strong><small><ArrowUpRight size={13}/> updates after approval</small></div><div className="stat"><span>Agents standing by</span><strong>5 <em>roles</em></strong><small><span className="dot"/> all connected</small></div></section>
      <div className="workspace"><section className="tickets"><div className="section-head"><div><div className="kicker">The queue</div><h2>Open tickets</h2></div><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={17}/></button></div>{tickets.map(t=><button className={`ticket ${t.id===selected?'selected':''}`} key={t.id} onClick={()=>setSelected(t.id)}><div className={`ticket-icon ${t.status==='resolved'?'done':''}`}>{t.status==='resolved'?<BadgeCheck size={20}/>:<CircleDot size={20}/>}</div><div className="ticket-info"><div className="ticket-line"><strong>#{t.id} · {t.subject}</strong><span className={`status ${t.status}`}>{t.status}</span></div><p>{t.requester} <span>·</span> {t.type.replaceAll('_',' ')}</p></div><ChevronRight size={18}/></button>)}</section>
        <section className="command"><div className="section-head"><div><div className="kicker">Selected request</div><h2>{ticket?`#${ticket.id} ${ticket.subject}`:'Select a ticket'}</h2></div>{ticket&&<span className={`pill ${ticket.status}`}>{ticket.status==='open'?'Needs attention':'Resolved'}</span>}</div>{ticket&&<><div className="request-card"><div className="request-meta"><span>FROM</span><strong>{ticket.requester}</strong></div><div className="request-meta"><span>TYPE</span><strong>{ticket.type.replaceAll('_',' ')}</strong></div><div className="request-meta"><span>DETAILS</span><strong>{ticket.sku?`${ticket.sku} · ${ticket.size} · qty ${ticket.qty}`:'Lease-linked request'}</strong></div><p>{ticket.notes}</p></div><div className="run-row"><button className="run-btn" onClick={run} disabled={running||ticket.status==='resolved'}>{running?<><span className="spinner"/> Team is thinking…</>:<><Sparkles size={17}/> Start agent team</>}</button>{pendingApproval&&<button className="approve-btn" onClick={approve}><ShieldCheck size={17}/> Approve payment</button>}</div>{message&&<div className="message">{message}</div>}<div className="section-head activity-head"><div><div className="kicker">Live transcript</div><h2>Agent activity</h2></div><span className="event-count">{ticketEvents.length} events</span></div><div className="feed">{ticketEvents.length===0?<div className="empty"><Bot size={24}/><p>Start the team to see their work appear here.</p></div>:ticketEvents.map((e,i)=><div className="event" key={`${e.run_id}-${e.step}-${i}`}><div className={`agent-avatar ${colors[e.agent]}`} >{React.createElement(icons[e.agent]??Bot,{size:15})}</div><div className="event-body"><div><strong>{agentNames[e.agent]??e.agent}</strong><span className="event-action">{e.action.replace('_',' ')}</span></div><p>{e.detail}</p>{e.tool_name&&<code>⌁ {e.tool_name}</code>}</div></div>)}</div></>}</section></div>
    </main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
